#include "gpio.h"


GPIO(const uint32_t GPIO_BASE ):
 GPIO_P((GPIO_TypeDef*)( GPIO_BASE))
{

}

 GPIO::setSPIMode()
 {
   /*
   SPI0_REMAP = 0
   PA4(SPI0_NSS)
   PA5(SPI0_SCK)
   PA6(SPI0_MISO)
   PA7(SPI0_MOSI)
   */

   GPIO_P->CTL0 &= ~(GPIO_CTL0_PIN_4_CB_MASK| GPIO_CTL0_PIN_4_MD_MASK | GPIO_CTL0_PIN_5_CB_MASK| GPIO_CTL0_PIN_5_MD_MASK | GPIO_CTL0_PIN_6_CB_MASK| GPIO_CTL0_PIN_6_MD_MASK|GPIO_CTL0_PIN_7_CB_MASK| GPIO_CTL0_PIN_7_MD_MASK  );

   GPIO_P->CTL0 |= ( GPIO_CTL0_PIN_4_MD_OUTPUT_50HZ|GPIO_CTL0_PIN_4_CB_AFIO_OUTPUT_PUSH_PULL|GPIO_CTL0_PIN_5_MD_OUTPUT_50HZ|GPIO_CTL0_PIN_5_CB_AFIO_OUTPUT_PUSH_PULL|GPIO_CTL0_PIN_7_MD_OUTPUT_50HZ|GPIO_CTL0_PIN_7_CB_AFIO_OUTPUT_PUSH_PULL);

   GPIO_P>CTL0 |= (GPIO_CTL0_PIN_6_MD_INPUT|GPIO_CTL0_PIN_6_CB_INPUT_FLOAT);

 }
